# general settings for OpenCEM

loop_time: 60  # time for the loops in seconds
simulation_speed: 1.0  # put 1 here if system is not simulated

# local web server
ip_address: "0.0.0.0"
port: 8000

# MQTT broker
mqtt_address: "localhost"
mqtt_port: 1883

# InfluxDB server
influxDB_address: "localhost"
influxDB_port: 8086
influxDB_user: ""
influxDB_password: ""
