# actual device and controller configuration of OpenCEM

installationName: SimTest
creationTimestamp: 2024-09-26 08:55:00
version: 1
communicationChannels: null
devices:
- name: Main Meter
  type: POWER_SENSOR
  smartGridreadyEID: null
  nativeEID: null
  simulationModel: MAIN_POWER
  isLogging: true
  communicationChannel: none
  extra:
    address: null
    hasEnergyImport: true
    hasEnergyExport: true
    maxPower: 10
- name: PV production
  type: POWER_SENSOR
  SmartGridreadyEID: none
  nativeEID: null
  simulationModel: PV_PLANT
  isLogging: true
  communicationChannel: none
  extra:
    address: null
    maxPower: 10
    hasEnergyImport: true
    hasEnergyExport: false
- name: Temperature Sensor Living Room
  type: TEMPERATURE_SENSOR
  smartGridreadyEID: null
  nativeEID: null
  simulationModel: ROOM_TEMPERATURE
  communicationChannel: null
  isLogging: true
  extra:
    address: null
    maxTemp: 50
    minTemp: -10
- name: Electric Heater Switch
  type: RELAIS_SWITCH
  smartGridreadyEID: null
  nativeEID: null
  simulationModel: ELECTRIC_HEATER
  isLogging: true
  communicationChannel: null
  extra:
    address: null
    nChannels: 1
- name: EV Charging Station
  type: EV_CHARGER
  smartGridreadyEID: null
  nativeEID: null
  simulationModel: EV_CHARGER
  isLogging: true
  communicationChannel: null
  extra:
    address: null
    port: null
    minPower: 4
    maxPower: 11
    phases: THREE_PHASES
- name: Heat Pump
  type: HEAT_PUMP
  smartGridreadyEID: null
  nativeEID: null
  simulationModel: HEAT_PUMP
  isLogging: true
  communicationChannel: null
  extra:
    address: null
    port: null
    minPower: 3
    maxPower: 5
controllers:
- name: EV Charge Controller
  type: DYNAMIC_EXCESS_CONTROLLER
  mainMeter: Main Meter
  deviceMeter: null
  controlledDevice: EV Charging Station
  functionalProfile: null
  controllerSettings:
      powerLimit: 4
      powerHysteresis: 0.5
- name: Electric Heating Controller
  type: SWITCHING_EXCESS_CONTROLLER
  mainMeter: Main Meter
  deviceMeter: null
  controlledDevice: Electric Heater Switch
  functionalProfile: null
  controllerSettings:
    powerLimit: 2
    powerHysteresis: 0.5
- name: Heat Pump DHW Controller
  type: TEMPERATURE_EXCESS_CONTROLLER
  mainMeter: Main Meter
  deviceMeter: Heat Pump Meter
  controlledDevice: Heat Pump
  functionalProfile: DHW
  controllerSettings:
    powerLimit: -999999   # always ON
    powerHysteresis: 0
    tempEco: 40
    excessComfort: 2
    tempComfort: 50
    excessMax: 10
    tempMax: 60

