installationName: Test
creationTimestamp: 2024-09-26 08:55:00
version: 1
communicationChannels:
- type: MODBUS_TCP
  extra: 
    adress: 127.0.0.1
    port: 502
- type: MODBUS_RTU
  extra:
    baudrate: 19200
    parity: EVEN
    port: /dev/ttyUSB0
- type: HTTP_LOCAL
  extra: none
- type: SHELLY_CLOUD
  extra:
    authKey: MTUyNjU5dWlk6D393AB193944CE2B1D84E0B573EAB1271DA6F2AF2BC54F67779F5BC27C31E90AD7C7075E0F813D8
    serverAddress: https://shelly-54-eu.shelly.cloud/
- type: SMARTME_CLOUD
  extra:
    authKey: SDFJDSLFKJAÖSLKFJÖSDLKJFSÖDLKJFLSKJADFÖLJ
    serverAddress: https://smartme.cloud/
sensors:
- name: Main Meter
  type: POWER_SENSOR
  smartGridreadyEID: Shelly3EM
  nativeEID: null
  simulationModel: MAIN_POWER
  isLogging: true
  communicationChannel: HTTP_LOCAL
  extra:
    address: 192.168.0.26
    hasEnergyImport: true
    hasEnergyExport: true
    maxPower: 10
- name: Heat Pump Consumption
  type: POWER_SENSOR
  smartGridreadyEID: ABB123
  nativeEID: null
  simulationModel: null
  isLogging: true
  communicationChannel: MODBUS_RTU
  extra:
    address: '1'
    maxPower: 10
    hasEnergyImport: false
    hasEnergyExport: false
- name: PV production
  type: POWER_SENSOR
  SmartGridreadyEID: ABB123
  nativeEID: null
  simulationModel: PV_PLANT
  isLogging: true
  communicationChannel: MODBUS_RTU
  extra:
    address: '2'
    maxPower: 10
    hasEnergyImport: true
    hasEnergyExport: false
- name: Temperature Sensor Living Room
  type: TEMPERATURE_SENSOR
  smartGridreadyEID: null
  nativeEID: Shelly_HT.yaml
  simulationModel: ROOM TEMPERATURE
  communicationChannel: SHELLY_CLOUD
  isLogging: true
  extra:
    address: 1f76d8
    maxTemp: 50
    minTemp: -10
actuators:
- name: Electric Heater Switch
  type: RELAIS_SWITCH
  smartGridreadyEID: null
  nativeEID: Shelly_2PM
  isLogging: true
  communicationChannel: HTTP_LOCAL
  extra:
    address: 192.168.0.210
    nChannels: 2
devices:
- name: EV Charging Station
  type: EV_CHARGER
  smartGridreadyEID: Pico123
  nativeEID: null
  simulationModel: EV_CHARGER
  isLogging: true
  communicationChannel: SMARTME_CLOUD
  extra:
    address: '10.0.0.220'
    port: '255'
    minPower: 4
    maxPower: 11
    phases: THREE_PHASES
- name: Heat Pump
  type: HEAT_PUMP
  smartGridreadyEID: Stiebel123
  nativeEID: null
  simulationModel: HEAT_PUMP
  isLogging: true
  communicationChannel: MODBUS_TCP
  extra:
    address: '10.1.1.200'
    port: '502'
    minPower: 3
    maxPower: 5
controllers:
- name: EV Charge Controller
  type: DYNAMIC_EXCESS_CONTROLLER
  mainMeter:
    sensor name: Main Meter
  controlledDevice:
    device name: EV Charging Station
  controllerSettings:
      power_switching: 4
- name: Electric Heating Controller
  type: SWITCHING_EXCESS_CONTROLLER
  mainMeter:
    sensor name: Main Meter
  controlledDevice:
    actuator name: Electric Heater Switch
    device name: null
    channel: 1
  controllerSettings:
    power_switching: 2
- name: Heat Pump DHW Controller
  type: TEMPERATURE_EXCESS_CONTROLLER
  mainMeter:
    sensor name: Main Meter
  deviceMeter:
    sensor name: Heat Pump Meter
  controlledDevice:
    device name: Heat Pump
    functional profile: DHW
  controllerSettings:
    temp_eco: 40
    excess_comfort: 2
    temp_comfort: 50
    excess_max: 10
    temp_max: 60

